### ISSUE TITLE
Special cards deck is created 3 times

### ISSUE THREAD

**Issue by grzegorzsobocinski2397** [smncru/herbs-game#5]
Special cards deck (mint, thyme, chive) is created in a for loop. It should be created only once.
```
 for(let i = 0; i < GameConstants.SPECIAL_HERBS_COUNT; i++) {
      this.deck.push(this.cardFactory.getSpecialCard(SpecialCardType.Mint));
      this.deck.push(this.cardFactory.getSpecialCard(SpecialCardType.Chive));
      this.deck.push(this.cardFactory.getSpecialCard(SpecialCardType.Thyme));
    }
```

Code reference:
https://github.com/sskorka/herbs-game/blob/1d2549b9702da380d5752180e6fac3b4710786d5/src/app/game/singleplayer/game-manager.service.ts#L462

Example:
<img width="868" alt="Duplicated mint card in a singleplayer game" src="https://user-images.githubusercontent.com/43864376/111590742-cd259a00-87c6-11eb-9777-3b5c18f69721.PNG">

**Comment by grzegorzsobocinski2397** [comment]
My mistake. There are 9 special cards in a deck 😑

<img width="278" alt="Capture" src="https://user-images.githubusercontent.com/43864376/111591234-78365380-87c7-11eb-8c7b-aff93be1889b.PNG">

**Comment by grzegorzsobocinski2397** [comment]
.eslintrc.json
```
{
  "env": {
    "browser": true,
    "es2021": true,
    "jasmine": true
  },
  "extends": ["airbnb-base", "eslint:recommended", "plugin:@typescript-eslint/recommended"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint"],
  "rules": {
    "require-jsdoc": ["off"],
    "new-cap": ["off"],
    "object-curly-spacing": ["off"],
    "max-len": ["off"],
    "import/no-unresolved": ["off"],
    "import/prefer-default-export": ["off"],
    "comma-dangle": ["off"],
    "linebreak-style": ["off"],
    "import/order": ["off"],
    "import/extensions": ["off"],
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": ["error"],
    "class-methods-use-this": ["off"],
    "object-curly-newline": "off",
    "no-shadow": "off",
    "no-useless-constructor": "off"
  }
}
```
.eslintignore
```
main.ts
polyfills.ts
test.ts
index.html
karma-ci-cd.conf.js
karma.conf.js
**/*.ico
**/*.html
**/*.json
**/*.ttf
**/*.txt
**/*.svg
**/*.scss
```

**Comment by grzegorzsobocinski2397** [comment]
Field:
`private destroy$ = new Subject();`

Metoda:
`   
 /** Wraps observable so it will unsubscribe on component destroy */
    private untilDestroy<T>(observable: Observable<T>): Observable<T> {
        return observable.pipe(takeUntil(this.destroy$));
    }
`

Użycie:
`
this.untilDestroy(this.store.select(resourceUsageTable)).subscribe((resUsage) => {
            this.table = { ...resUsage };
            this.initResources();
        });
`

Koniec:
`    
ngOnDestroy(): void {
        this.destroy$.next(null);
        this.destroy$.complete();
    }
`

**Comment by grzegorzsobocinski2397** [comment]
Ale to u góry jest dziwne jak dla mnie i chyba akurat trafiłem na jedyny przypadek tego.

Normalnie jest bez dodatkowej metody.
`.pipe(takeUntil(this.destroy$))`

**Comment by sskorka** [comment]
This isn't a public notepad, please refrain from posting personal notes and keep it Herbs Up! related. Thanks!
